package test_task.exceptions;

public final class TableFoundException extends RuntimeException{
    public TableFoundException(String message){super(message);}
}
